######################################################################
# Automatically generated by qmake (3.0) Mi Nov 18 12:01:06 2015
######################################################################

TEMPLATE = app
TARGET = hello
INCLUDEPATH += .
QT += widgets

# Input
SOURCES += hello.cpp
