######################################################################
# Automatically generated by qmake (3.0) Mi Nov 18 11:44:23 2015
######################################################################

TEMPLATE = app
TARGET = CppGuiProgrammingWithQt
INCLUDEPATH += .
QT += widgets
# Input
SOURCES += ex0103.cpp
