######################################################################
# Automatically generated by qmake (3.0) Mi Nov 18 18:45:44 2015
######################################################################

TEMPLATE = app
TARGET = ex0202GotoCell
INCLUDEPATH += .
QT += widgets

# Input
FORMS += gotocelldialog.ui
SOURCES += main.cpp \
    gotocelldialog.cpp

HEADERS += \
    gotocelldialog.h
